services:
  telescent-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telescent-backend
    ports:
      - "5001:5001"
    environment:
      NODE_ENV: production
      PORT: 5001
      DOCKER_ENV: "true"
    volumes:
      - ./backend/database.sqlite:/app/database.sqlite
      - ./collected_data:/collected_data
    networks:
      - telescent-network

networks:
  telescent-network:
    driver: bridge
