#!/bin/bash
# Quick reference for Render.com deployment

echo "🚀 Render.com Deployment - Quick Steps"
echo "======================================="
echo ""
echo "✅ Step 1: DONE - Code pushed to GitHub"
echo ""
echo "📋 Step 2: Deploy on Render.com"
echo ""
echo "1. Go to: https://render.com"
echo ""
echo "2. Sign up/Login with GitHub (DomJab23)"
echo ""
echo "3. Click 'New +' → 'Web Service'"
echo ""
echo "4. Connect repository: DomJab23/TeleScent"
echo ""
echo "5. Configure:"
echo "   Name:           telescent-backend"
echo "   Region:         Oregon (Free)"
echo "   Branch:         main"
echo "   Root Directory: backend"
echo "   Build Command:  npm install"
echo "   Start Command:  node server.js"
echo "   Plan:           Free"
echo ""
echo "6. Click 'Create Web Service'"
echo ""
echo "7. Wait ~5 minutes for deployment"
echo ""
echo "8. Your URL will be: https://telescent-backend-xxxx.onrender.com"
echo ""
echo "======================================="
echo "After deployment, update ESP32:"
echo ""
echo "Edit: embedded /enose/include/main.h"
echo ""
echo "  #define HOST_NAME \"telescent-backend-xxxx.onrender.com\""
echo "  #define PORT 443"
echo ""
echo "Then upload to ESP32:"
echo "  cd \"embedded /enose\""
echo "  pio run -e gsm_test -t upload"
echo "  pio device monitor"
echo ""
echo "======================================="
echo "✨ Your backend will be accessible worldwide!"
echo "   Perfect for GSM cellular connections!"
echo ""
